name: 'code coverage'
on:
    pull_request:
        branches: '*'

jobs:
    create-report:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80